let a = null; // Armazena data formatada
let b = null; // Armazena dia da semana
let c = null; // Armazena horário

const translationsAdulto = {
    pt: {
        voltar: "Voltar",
        tituloPagina: "Agendamento",
        tipoAtendimento: "Atendimento selecionado: Adulto",
        profissionalEncontrada: "Profissional encontrada: Vagner",
        especialidade: "Especialista em: Desenvolvimento Pessoal",
        mesAnterior: "Mês anterior",
        proximoMes: "Próximo mês",
        domingo: "DOM",
        segunda: "SEG",
        terca: "TER",
        quarta: "QUA",
        quinta: "QUI",
        sexta: "SEX",
        sabado: "SAB",
        qualHorarioMelhor: "Qual o horário é melhor?",
        fusoHorario: "UTC -3 (Horário de Brasília)",
        resumoAgendamento: "Resumo do Agendamento:",
        dataSelecionada: "Data Selecionada:",
        horarioSelecionado: "Horário Selecionado:",
        confirmarAgendamento: "Confirmar Agendamento",
        selecioneDiaHorario: "Por favor, selecione um dia e um horário para agendar",
        agendamentoConfirmado: "Agendamento Confirmado!",
        consultaAgendadaSucesso: "Consulta agendada com sucesso!",
        detalhesAgendamento: "Sua consulta com {0} está marcada para: {1} às {2}",
        fecharModal: "Fechar",
        janeiro: "Janeiro",
        fevereiro: "Fevereiro",
        marco: "Março",
        abril: "Abril",
        maio: "Maio",
        junho: "Junho",
        julho: "Julho",
        agosto: "Agosto",
        setembro: "Setembro",
        outubro: "Outubro",
        novembro: "Novembro",
        dezembro: "Dezembro",
        tituloMeusAgendamentos: "Meus Agendamentos",
        semAgendamentos: "Nenhum agendamento encontrado.",
        dataAgendamento: "Data:",
        horarioAgendamento: "Horário:",
        profissionalAgendamento: "Profissional:",
        cancelarAgendamento: "Excluir",
        baixarRelatorio: "Baixar Relatório"
    },
    en: {
        voltar: "Back",
        tituloPagina: "Scheduling",
        tipoAtendimento: "Selected Service: Adult",
        profissionalEncontrada: "Professional found: Vagner",
        especialidade: "Specialist in: Personal Development",
        mesAnterior: "Previous month",
        proximoMes: "Next month",
        domingo: "SUN",
        segunda: "MON",
        terca: "TUE",
        quarta: "WED",
        quinta: "THU",
        sexta: "FRI",
        sabado: "SAT",
        qualHorarioMelhor: "What time works best?",
        fusoHorario: "UTC -3 (Brasilia Time)",
        resumoAgendamento: "Appointment Summary:",
        dataSelecionada: "Selected Date:",
        horarioSelecionado: "Selected Time:",
        confirmarAgendamento: "Confirm Appointment",
        selecioneDiaHorario: "Please select a day and time to schedule",
        agendamentoConfirmado: "Appointment Confirmed!",
        consultaAgendadaSucesso: "Appointment scheduled successfully!",
        detalhesAgendamento: "Your appointment with {0} is scheduled for: {1} at {2}",
        fecharModal: "Close",
        janeiro: "January",
        fevereiro: "February",
        marco: "March",
        abril: "April",
        maio: "May",
        junho: "June",
        julho: "July",
        agosto: "August",
        setembro: "September",
        outubro: "October",
        novembro: "November",
        dezembro: "December",
        tituloMeusAgendamentos: "My Appointments",
        semAgendamentos: "No appointments found.",
        dataAgendamento: "Date:",
        horarioAgendamento: "Time:",
        profissionalAgendamento: "Professional:",
        cancelarAgendamento: "Delete",
        baixarRelatorio: "Download Report"
    },
    es: {
        voltar: "Volver",
        tituloPagina: "Programación",
        tipoAtendimento: "Servicio seleccionado: Adulto",
        profissionalEncontrada: "Profesional encontrado: Vagner",
        especialidade: "Especialista en: Desarrollo Personal",
        mesAnterior: "Mes anterior",
        proximoMes: "Próximo mes",
        domingo: "DOM",
        segunda: "LUN",
        terca: "MAR",
        quarta: "MIÉ",
        quinta: "JUE",
        sexta: "VIE",
        sabado: "SÁB",
        qualHorarioMelhor: "¿Qué horario es mejor?",
        fusoHorario: "UTC -3 (Hora de Brasilia)",
        resumoAgendamento: "Resumen de la Cita:",
        dataSelecionada: "Fecha Seleccionada:",
        horarioSelecionado: "Hora Seleccionada:",
        confirmarAgendamento: "Confirmar Cita",
        selecioneDiaHorario: "Por favor, seleccione un día y una hora para programar",
        agendamentoConfirmado: "¡Cita Confirmada!",
        consultaAgendadaSucesso: "¡Cita programada con éxito!",
        detalhesAgendamento: "Su cita con {0} está programada para: {1} a las {2}",
        fecharModal: "Cerrar",
        janeiro: "Enero",
        fevereiro: "Febrero",
        marco: "Marzo",
        abril: "Abril",
        maio: "Mayo",
        junho: "Junio",
        julho: "Julio",
        agosto: "Agosto",
        setembro: "Septiembre",
        outubro: "Octubre",
        novembro: "Noviembre",
        dezembro: "Diciembre",
        tituloMeusAgendamentos: "Mis Citas",
        semAgendamentos: "No se encontraron citas.",
        dataAgendamento: "Fecha:",
        horarioAgendamento: "Hora:",
        profissionalAgendamento: "Profesional:",
        cancelarAgendamento: "Eliminar",
        baixarRelatorio: "Descargar Informe"
    }
};